name: ecuaranch
description: "A new Flutter project."

publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  http: ^1.3.0 
  easy_localization: ^3.0.7+1
  geolocator: ^13.0.0
  permission_handler: ^11.4.0
  weather: ^3.2.1
  web_socket_channel: ^3.0.0
  flutter_local_notifications: ^18.0.0
  image_picker: ^1.1.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Dependencia para buenas prácticas de codificación

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logoecuaranch.png
    - assets/images/logoecuabyte.png
    - assets/icons/
    - assets/translations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoecuaranch.png"

flutter_native_splash:
  background_image: assets/icons/fondo.png
  image: assets/icons/Logo@300x.png
  android: true
  ios: true
  web: false

  fullscreen: true
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: assets/images/test001.png
    icon_background_color: "#ffffff"
