name: ecuaranch
description: "A new Flutter project."

publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0 
  easy_localization: ^3.0.7+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Dependencia para buenas prácticas de codificación

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/campo_ganadero.png
    - assets/images/logoecuabyte.png
    - assets/translations/



  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
