name: ecuaranch
description: "A new Flutter project."

publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  http: ^1.3.0 
  easy_localization: ^3.0.7+1
  geolocator: ^13.0.0
  weather: ^3.2.1
  web_socket_channel: ^3.0.0
  flutter_local_notifications: ^18.0.0
  image_picker: ^1.1.0
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Dependencia para buenas prácticas de codificación

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logoecuaranch.png
    - assets/images/logoecuabyte.png
    - assets/icons/
    - assets/translations/


flutter_native_splash:
  color: "#ffffff"  # color de fondo
  image: assets/images/logoecuaranch.png  # Imagen que quieres mostrar
  android: true  # Splash en Android
  ios: true  # Splash en iOS
  web: false  # No utilizar splash en Web (opcional)

  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
